// Comprehensive Czech-English translation corrections
// Format: czech word -> correct English translation

module.exports = {
  // Basic words - context-dependent, use most common meaning
  'ten': 'that/the',
  'člověk': 'person',
  'stát': 'state/stand',
  'velký': 'big',
  'hodně': 'a lot',
  'každý': 'every',
  'druhý': 'second',
  'strana': 'side/party',
  'ne': 'no',
  'dobře': 'well',
  'asi': 'probably',
  'cesta': 'way/road',
  'poslední': 'last',
  'dům': 'house',
  'část': 'part',
  'lze': 'it is possible',
  'firma': 'company',
  'moc': 'very/power',
  'problém': 'problem',
  'řada': 'row/series',
  'rozhodnout': 'decide',
  'výsledek': 'result',
  'procento': 'percent',
  'kvůli': 'because of',
  'noha': 'leg/foot',
  'jistý': 'certain',
  'přímo': 'directly',
  'hodina': 'hour',
  'obraz': 'picture',
  'cíl': 'goal',
  'silný': 'strong',
  'proces': 'process',
  'podařit se': 'succeed',
  'těžký': 'difficult/heavy',
  'rada': 'advice/council',
  'přítel': 'friend',
  'kraj': 'region',
  'období': 'period',
  'zároveň': 'at the same time',
  'zvláštní': 'special',
  'obec': 'municipality',
  'náklad': 'cost/load',
  'obchod': 'shop/trade',
  'umět': 'know how to',
  'pán': 'gentleman/Mr.',
  'tvořit': 'create',
  'svatý': 'holy/saint',
  'poprvé': 'for the first time',
  'vzniknout': 'arise',
  'věnovat': 'dedicate',
  'pravý': 'right/true',
  'poznat': 'recognize',
  'nabízet': 'offer',
  'vlas': 'hair',
  'list': 'leaf/letter',
  'použít': 'use',
  'podpora': 'support',
  'prosit': 'please/ask',
  'jenže': 'but',
  'energie': 'energy',
  'doprava': 'transport',
  'zvíře': 'animal',
  'správný': 'correct',
  'silnice': 'road',
  'jednoduchý': 'simple',
  'dnešní': "today's",
  'využít': 'utilize',
  'zrovna': 'just now',
  'kolo': 'wheel/bike',
  'jazyk': 'language',

  // More corrections
  'praxe': 'practice',
  'výraz': 'expression',
  'stěhovat': 'move',
  'nést': 'carry',
  'úspěšný': 'successful',
  'obrat': 'turnover',
  'kůň': 'horse',
  'nebe': 'sky',
  'jedno': 'one',
  'fotbal': 'football',
  'spojit': 'connect',
  'pátek': 'Friday',
  'chyba': 'mistake',
  'tisk': 'press',
  'soused': 'neighbor',
  'přírodní': 'natural',
  'prodávat': 'sell',
  'kapela': 'band',
  'provést': 'perform',
  'zavést': 'introduce',
  'odkud': 'from where',
  'potíž': 'trouble',
  'zadek': 'back/bottom',
  'linka': 'line',
  'padat': 'fall',
  'podstatný': 'essential',
  'zítřek': 'tomorrow',
  'výhoda': 'advantage',
  'nárok': 'claim',
  'dosavadní': 'current',
  'brzký': 'early',
  'dotknout se': 'touch',
  'hrozit': 'threaten',
  'naučit': 'teach',
  'pusa': 'kiss/mouth',
  'přání': 'wish',
  'srdečný': 'heartfelt',
  'stupeň': 'degree',
  'zajímat': 'interest',
  'sbírat': 'collect',
  'světelný': 'light',
  'spočítat': 'count',
  'tvrzení': 'claim',
  'účast': 'participation',
  'upozornit': 'warn',
  'vážit': 'weigh',
  'závod': 'race/factory',
};

// Words to completely remove (not useful for vocab learning)
module.exports.removeWords = [
  '-li',      // suffix, not standalone
  'de',       // not Czech
  'ČR',       // abbreviation
  'ČSSD',     // political party
  'Sb',       // legal reference
  'Kč',       // currency symbol
  'aj',       // abbreviation
  'atd',      // abbreviation (etc.)
  'apod',     // abbreviation
  'tzn',      // abbreviation
  'resp',     // abbreviation
  'tzv',      // abbreviation
  'mj',       // abbreviation
  'cca',      // abbreviation
  'cit',      // abbreviation
];
